name-template: "v$RESOLVED_VERSION"   # version-resolver에 정의한 Labels에 따라 버전을 올린다.
tag-template: "v$RESOLVED_VERSION"    # version-resolver에 정의한 Labels에 따라 버전을 올린다.
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
version-resolver:   # major, minor, patch를 정의하고 그 외에는 patch 버전을 올린다.
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |   # 릴리즈 노트 형식을 정의한다.
  ## Changes
  ---
  $CHANGES